services:

  control_de_manejo:
      build:
        context: $PWD
        dockerfile: $PWD/Dockerfile
      image: control_de_manejo
      container_name: control_de_manejo
      hostname: control_de_manejo
      read_only: false
      healthcheck:
          test: ["CMD-SHELL", "exit 0"]
          interval: 5m
      environment:
        DISPLAY: $DISPLAY
        HOSTXAUTH: "/tmp/host-xauth"
        XAUTHORITY: /tmp/.Xauthority
        QT_X11_NO_MITSHM: 1
        AppName: "Control_de_manejo"
      volumes:
        - "/dev:/dev"
        - "/var/tmp:/var/tmp"
        - "/opt/altera:/opt/altera"
        - "${HOME}/.Xauthority:/tmp/host-xauth:ro"
        - "/tmp/.X11-unix:/tmp/.X11-unix"
        - "${PWD}/frontend/public/eventos:/eventos"
      privileged: true
      devices:
        - "/dev/:/dev/"
      ports:
      - "8765:8765"
      - "8766:8766"
  drivers_api:
      build:
        context: $PWD/drivers_endpoint
        dockerfile: $PWD/drivers_endpoint/Dockerfile
      image: drivers_api
      container_name: drivers_api
      hostname: drivers_api
      read_only: false
      healthcheck:
          test: ["CMD-SHELL", "exit 0"]
          interval: 5m
      environment:
        AppName: "drivers_api"
      volumes:
        - "/dev:/dev"
      privileged: false
      ports:
      - "8000:8000"